#
# This file is the configuration file used for the run of the hFE pipeline, modified from Denis's config_noPSL.yaml.
#
# Author: Mathieu Simon, ARTORG Center for Biomedical Engineering Research, SITEM Insel, University of Bern
# Date: October 2021
#
# No padding
#

# Run/hFE version (for file names)
Version: '00'

# State if properties must be computed using transform or in original configuration
Registration: False

# Define element size
ElementSize: 1.2747
Adjust_ElementSize: True

# Scaling for BV/TV -> 0: no scaling, 1: Hosseini 2017 Seg scaling
BVTV_Scaling: 1

# Custom BV/TV scaling if BVTV_Scaling == 0
BVTV_Slope: 1
BVTV_Intercept: 0

# Parameters to compute mean surface length (MSL) fabric (Hosseini 2017)
STL_Tolerance: 0.2
ROI_Kernel_Size_Cort: 5
ROI_Kernel_Size_Trab: 5

# Diameter of sphere with same volume as FEelement (3./4*(Volume_FEelement/math.pi))**(1./3)*2
ROI_BVTV_Size_Cort: 1.3453
ROI_BVTV_Size_Trab: 4

# Parameters for cortex
Isotropic_Cortex: False  # Cortex fabric isotropic, or projected on surface

# Elements containing part of a mask are converted to FE mesh, even if they don't hold BVTV. In this case, BVTV is set to 1%.
All_Mask: True

# Simulation parameters
nlgeom: on # affects NLGEOM parameter in abaqus simulation (on/off)
Max_Increments: 1000  # int number [1-1000]
Control: Displacement # [Force/Displacement] discribes the loading boundary conditions
BCs_Mode: 5           # 0: all DOF fixed / 2: two in plane fixed / 5: all DOF free
Fz_Max_Factor: 1.0    # Displacement in FZ direction for no psl FZ_MAX
BCs_Load: [[1.0, 0, 0, 0, 0, 0],
           [0, 1.0, 0, 0, 0, 0],
           [0, 0, 1.0, 0, 0, 0],
           [0, 0, 0, 1.0, 0, 0],
           [0, 0, 0, 0, 1.0, 0],
           [0, 0, 0, 0, 0, 1.0]]

# Relative directories
BCs: 'BCs/boundary_conditions_basic.inp'
PSL_LoadCases_BCs_Folder: 'BCs/'


# File name post fixes
Postfix_CortMask: '_CORT_MASK.AIM'
Postfix_TrabMask: '_TRAB_MASK.AIM'
Postfix_BMD: '.AIM'
Postfix_SEG: '_SEG.AIM'

# Images type
ImageType: "NATIVE"  # BMD/NATIVE

# Images
GrayScale_FileNames: [
    'C0001901_DOWNSCALED',
#    'C0003114',
#    'C0003111',
#    'C0003106',
#    'C0003113',
#    'C0003095',
#    'C0003104',
#    'C0003098',
#    'C0003097',
#    'C0003116',
#    'C0003093',
#    'C0003101',
#    'C0003115',
#    'C0003110',
#    'C0003091',
#    'C0003117',
#    'C0003096',
#    'C0003094',
#    'C0003099',
#    'C0003108',
#    'C0003102',
#    'C0003109',
#    'C0003118',
#    'C0003112',
#    'C0003105',
]

# Folder IDs for file-folder mapping
Folder_IDs:
  C0001901_DOWNSCALED: 432_L_77_F
  C0003114: 433_R_77_F
  C0003111: 434_L_90_F
  C0003106: 435_R_90_F
  C0003113: 436_L_90_F
  C0003095: 437_R_90_F
  C0003104: 438_L_71_F
  C0003098: 439_R_71_F
  C0003097: 440_L_64_M
  C0003116: 441_R_64_M
  C0003093: 442_R_75_F
  C0003101: 443_L_73_F
  C0003115: 444_R_92_F
  C0003110: 445_R_93_F
  C0003091: 446_R_75_F
  C0003117: 447_L_83_M
  C0003096: 448_L_80_M
  C0003094: 449_L_93_F
  C0003099: 450_L_77_F
  C0003108: 451_L_75_F
  C0003102: 452_L_75_F
  C0003109: 453_R_79_M
  C0003118: 454_L_94_F
  C0003112: 455_L_97_F
  C0003105: 456_R_97_F
