medtoolpath: "/home/ms20s284/3_SCRIPT/medtool/"
nphases: 1
ftype: "iso"
element_size: 1
verification_file: 1
roi_bvtv_size: 6.6
origaim_separate: False
all_mask: True  # if true, all elements containing part of a mask are converted to FE mesh, even if they don't hold
                # BVTV. In this case, BVTV is set to 1%.

filename_postfix_cort_mask: "_CORT_MASK_UNCOMP.AIM;1"
filename_postfix_trab_mask: "_TRAB_MASK_UNCOMP.AIM;1"
filename_postfix_bmd: "_UNCOMP.AIM;1"
filename_postfix_seg: "_UNCOMP_SEG.AIM;1"
imtype: "NATIVE"  # BMD/NATIVE

site: "remote" # local or remote
# Directories
workdir: "/home/ms20s284/FRACTIB/"
aimdir:  "/home/ms20s284/FRACTIB/1_AIM/"
origaimdir: "/home/ms20s284/FRACTIB/1_AIM/"
feadir:  "/home/ms20s284/FRACTIB/2_FEA"
umat: "/home/ms20s284/FRACTIB/3_SCRIPT/UMAT_homogenization_PSL_accurate.f"
sumdir: "/home/ms20s284/FRACTIB/Summaries/"
boundary_conditions: "/home/ms20s284/FRACTIB/boundary_conditions.inp"
odb_python_script: "/home/ms20s284/FRACTIB/3_SCRIPT/readODB_acc.py"
odb_OF_python_script: "/home/ms20s284/FRACTIB/3_SCRIPT/readODB_OF.py"
verification_files: 1

#MSL_kernel_list_path: "/home/ms20s284/FRACTIB/1_AIM/MSL_kernel_list_shortcut.npy"

#abaqus: 'abq6141' # monterosa (Abaqus 2016)
abaqus: 'abaqus'  # cortex and skull (Abaqus 2020)

current_version: "10_first_official_run"

# Images
grayscale_filenames: [
   "C0003103",
#    "C0003114",
#    "C0003111",
#    "C0003106",
#    "C0003113",
#    "C0003095",
#    "C0003104",
#    "C0003098",
#    "C0003097",
#    "C0003116",
#    "C0003093",
#    "C0003101",
#    "C0003115",
#    "C0003110",
#    "C0003091",
#    "C0003117",
#    "C0003096",
#    "C0003094",
#    "C0003099",
#    "C0003108",
#    "C0003102",
#    "C0003109",
#    "C0003118",
#    "C0003112",
#    "C0003105",
]


# MSL fabric
STL_tolerance: 0.2
ROI_kernel_size: 5
ROI_BVTV_size_cort: 1.241 # Diameter of sphere with same volume as FEelement (3./4*(Volume_FEelement/math.pi))**(1./3)*2
ROI_BVTV_size_trab: 2.481 # Diameter
fabric_type: 'iso' # 'local' or 'global' or 'iso' - 'global not working at the moment
bvtv_scaling: 1 # 0: no scaling, 1: Hosseini 2017 Seg scaling

# Boundary conditions
folder_bc_psl_loadcases: "/home/ms20s284/FRACTIB/BC_PSL/"
control: displacement # [force/displacement] discribes the loading boundary conditions
start_step_size: 0.05
time_for_displacement: 4.8
min_step_size: 0.00005
max_step_size: 0.05
load_displacement: 2.78

shift_refnode_x: 0.0 # shift of ref node in positive x-direction [mm]
shift_refnode_y: 0.0 # shift of ref node in positive y-direction [mm]
shift_refnode_z: 0.0 # shift of ref node in positive z-direction [mm]

#bc_load: [[49.0, 0, 0, 0, 0, 0],
#          [0, 49.0, 0, 0, 0, 0],
#          [0, 0, 49.0, 0, 0, 0],
#          [0, 0, 0, 28.0, 0, 0],
#          [0, 0, 0, 0, 28.0, 0],
#          [0, 0, 0, 0, 0, 28.0]]

bc_load: [[1.0, 0, 0, 0, 0, 0],
          [0, 1.0, 0, 0, 0, 0],
          [0, 0, 1.0, 0, 0, 0],
          [0, 0, 0, 1.0, 0, 0],
          [0, 0, 0, 0, 1.0, 0],
          [0, 0, 0, 0, 0, 1.0]]

# Patient specific loading
padding_elements_proximal: 0
padding_elements_distal: 0

mode_ghost_layer: 1 # 1: copy material properties; 2: predefined material properties
BVTV_ghost: 0.5 # only applied with ghost layer mode 2

# Optimization
OF_computation: no  # compute value of OF [yes/no]
statevar_optim: "E"
statevar_optim_max: "LE" # state variable for MAX loadcases (OPT_MAX, FZ_MAX)

target_frame: -1

var_r: 0
var_eps0: 0.001

lambda: 70  # scaling factor for OPT_MAX loadcase

# Simulation parameters
full_nonlinear_loadcases: True  # [True/False] compute non-linear loadcases [FX, FY, MX, MY, MZ]
# abaqus: '/home/jarunanp/software/Abaqus/build/6.14-1/Commands/abq6141'

nlgeom: off # affects NLGEOM parameter in abaqus simulation (on/off)
nprocs: 12

fz_max_factor: 0.6
fx_fy_max_factor: 1.3
mx_my_max_factor: 1
mz_max_factor: 0.8

# optim report variables
dpi_images: 100

sca1: 2.29
sca2: 2.30
kmax: 0.018

umat_parameters:
  KSLOPE: 1000.0
  KWIDTH: 8.0
  KMIN: 0.1
  GMIN: -2.0
  EXPS: 300.0
  ND: 2.0
  E0: 9759.0
  V0: 0.2278
  MU0: 3117.0
  KS: 1.91
  LS: 1.1
  SIGD0P: 57.69
  SIGD0N: 73.1
  ZETA0: 0.28
  TAUD0: 29.61
  PP: 1.82
  QQ: 0.98

# Folder IDs for HR Hosseini
folder_id:
  C0003103: 432_L_77_F
  C0003114: 433_R_77_F
  C0003111: 434_L_90_F
  C0003106: 435_R_90_F
  C0003113: 436_L_90_F
  C0003095: 437_R_90_F
  C0003104: 438_L_71_F
  C0003098: 439_R_71_F
  C0003097: 440_L_64_M
  C0003116: 441_R_64_M
  C0003093: 442_R_75_F
  C0003101: 443_L_73_F
  C0003115: 444_R_92_F
  C0003110: 445_R_93_F
  C0003091: 446_R_75_F
  C0003117: 447_L_83_M
  C0003096: 448_L_80_M
  C0003094: 449_L_93_F
  C0003099: 450_L_77_F
  C0003108: 451_L_75_F
  C0003102: 452_L_75_F
  C0003109: 453_R_79_M
  C0003118: 454_L_94_F
  C0003112: 455_L_97_F
  C0003105: 456_R_97_F
