#
# This file is the configuration file used for the run of the hFE pipeline, modified from Denis's config_noPSL.yaml.
#
# Author: Mathieu Simon, ARTORG Center for Biomedical Engineering Research, SITEM Insel, University of Bern
# Date: October 2021
#
# No padding
#

# Run/hFE version (for file names)
Version: 'Test'

# Define element size
ElementSize: 1

# Define fabric type -> Isotropic or Local
FabricType: 'Isotropic'

# Scaling for BV/TV -> 0: no scaling, 1: Hosseini 2017 Seg scaling
BVTV_Scaling: 1

# Parameters to compute mean surface length (MSL) fabric (Hosseini 2017)
STL_Tolerance: 0.2
ROI_Kernel_Size_Cort: 5
ROI_Kernel_Size_Trab: 5

# Diameter of sphere with same volume as FEelement (3./4*(Volume_FEelement/math.pi))**(1./3)*2
ROI_BVTV_Size_Cort: 1.241
ROI_BVTV_Size_Trab: 2.481

# Parameters for ghost layers
Isotropic_Cortex: False  # Cortex fabric isotropic, or projected on surface
Ghost_Layer_Mode: 1      # 1: copy material properties; 2: predefined material properties

# Elements containing part of a mask are converted to FE mesh, even if they don't hold BVTV. In this case, BVTV is set to 1%.
All_Mask: True

# Simulation parameters
nlgeom: off # affects NLGEOM parameter in abaqus simulation (on/off)
nprocs: 4
max_increments: 1000 # int number [1-1000]
Control: Force # [Force/Displacement] discribes the loading boundary conditions


# Relative directories
AIMDir:  '02_Data/05_hFE/01_AIM/'
FEADir:  '05_Results/05_hFE/'
BCs:     '02_Data/05_hFE/BC_PSL/boundary_conditions_basic.inp'
PSL_LoadCases_BCs_Folder: '02_Data/05_hFE/BC_PSL/'


# File name post fixes
Postfix_CortMask: '_CORT_MASK_UNCOMP.AIM'
Postfix_TrabMask: '_TRAB_MASK_UNCOMP.AIM'
Postfix_BMD: '_UNCOMP.AIM'
Postfix_SEG: '_UNCOMP_SEG.AIM'

# Images type
ImageType: "NATIVE"  # BMD/NATIVE

# Images
GrayScale_FileNames: [
    'C0003103',
#    'C0003114',
#    'C0003111',
#    'C0003106',
#    'C0003113',
#    'C0003095',
#    'C0003104',
#    'C0003098',
#    'C0003097',
#    'C0003116',
#    'C0003093',
#    'C0003101',
#    'C0003115',
#    'C0003110',
#    'C0003091',
#    'C0003117',
#    'C0003096',
#    'C0003094',
#    'C0003099',
#    'C0003108',
#    'C0003102',
#    'C0003109',
#    'C0003118',
#    'C0003112',
#    'C0003105',
]

# Folder IDs for file-folder mapping
Folder_IDs:
  C0003103: 432_L_77_F
  C0003114: 433_R_77_F
  C0003111: 434_L_90_F
  C0003106: 435_R_90_F
  C0003113: 436_L_90_F
  C0003095: 437_R_90_F
  C0003104: 438_L_71_F
  C0003098: 439_R_71_F
  C0003097: 440_L_64_M
  C0003116: 441_R_64_M
  C0003093: 442_R_75_F
  C0003101: 443_L_73_F
  C0003115: 444_R_92_F
  C0003110: 445_R_93_F
  C0003091: 446_R_75_F
  C0003117: 447_L_83_M
  C0003096: 448_L_80_M
  C0003094: 449_L_93_F
  C0003099: 450_L_77_F
  C0003108: 451_L_75_F
  C0003102: 452_L_75_F
  C0003109: 453_R_79_M
  C0003118: 454_L_94_F
  C0003112: 455_L_97_F
  C0003105: 456_R_97_F


